server:
  port: 10000

spring:
  jackson:
    default-property-inclusion : NON_NULL
  datasource:
    url: jdbc:postgresql://localhost:5432/order_manager
    username: testuser
    password: qwerty
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog-master.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'
clients:
  settings:
    warehouse-manager:
     root-uri: http://localhost:10000
     connection-timeout: 5s
     read-timeout: 10s
     connection-manager:
       default-max-per-route: 50
       max-total: 50